from app import app, db
from sqlalchemy import text
from werkzeug.security import generate_password_hash

def init_db():
    """
    1. Runs schema.sql to create tables and insert mock data.
    2. Updates all users' passwords to a valid hash generated by YOUR system.
    """
    with app.app_context():
        try:
            # Step 1: Execute Schema (Create Tables & Insert Rows)
            with open('schema.sql', 'r') as file:
                sql_script = file.read()
            
            with db.engine.connect() as connection:
                print("1. Executing schema.sql...")
                connection.execute(text(sql_script))
                
                # Step 2: Generate a valid hash for "password"
                print("2. Fixing password hashes...")
                valid_hash = generate_password_hash("password")
                
                # Step 3: Overwrite the passwords in the database
                # This ensures the hash in the DB matches what check_password_hash() expects
                update_query = text("UPDATE users SET password = :h")
                connection.execute(update_query, {'h': valid_hash})
                
                connection.commit()
                
            print("\n" + "="*50)
            print("✅ DATABASE INITIALIZED & PASSWORDS FIXED!")
            print("="*50)
            print("You can now log in with the password: 'password'")
            print("-" * 55)
            print(f"{'Admin':<15} | {'admin@demo.com':<25}")
            print(f"{'Instructor':<15} | {'instructor@demo.com':<25}")
            print(f"{'Student':<15} | {'student@demo.com':<25}")
            print(f"{'Analyst':<15} | {'analyst@demo.com':<25}")
            print("-" * 55)
            
        except Exception as e:
            print(f"❌ An error occurred: {e}")

if __name__ == '__main__':
    init_db()